name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run propertyFinder

      - name: Send Email Notification
        uses: softprops/action-email@v1
        with:
          to: cihan.aslan.qa@gmail.com
          subject: Test Report
          body: Test report is attached.
          files: /home/runner/work/PropertyAssignment/PropertyAssignment/cypress/results/*.html
        env:
          SMTP_SERVER: smtp.google.com
          SMTP_PORT: 465
          SMTP_USERNAME: ${{ secrets.USERNAME }}
          SMTP_PASSWORD: ${{ secrets.PASSWORD }}
