name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run propertyFinder

      - name: Zip Install
        run: sudo apt-get install zip -y

      - name: Zip report
        run: zip -r **/cypress/results.zip . -i **/cypress/results/*

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address if not connection_url:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: cihan.aslan.qa@gmail.com
          # Required sender full name (address can be skipped):
          from: cihan.aslan.qa@gmail.com
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: /home/runner/work/PropertyAssignment/PropertyAssignment/cypress/results.tar
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high
